<?php

/* De Array grandprixs is opgebouwt uit arrays die de data bevatten voor één specifieke grandprix.
                
                Opbouw array(   Videolink,
                                Locatie,
                                GP naam full,
                                img)    
*/
$grandprixs = array
            (
                array(  "https://www.youtube.com/watch?v=iFo6lyunfo8",
                        "Australia",
                        "Formula 1 Rolex Australian Grand Prix 2019",
                        "img/aus.jpg"),
                array(  "https://www.youtube.com/watch?v=iFo6lyunfo8",
                        "Bahrain",
                        'Formula 1 Gulf Air Bahrain Grand Prix 2019',
                        "img/bahrain.jpg"),
                array(  "#",
                        "China",
                        "Formula 1 Heineken Chinese Grand Prix 2019",
                        "img/china.jpg"),
                array(  "#",
                        "Azerbaijan",
                        "Formula 1 Socar Azerbaijan Grand Prix 2019",
                        "img/aze.jpg"),
                array(  "#",
                        "Spain",
                        "Formula 1 Emirates Gran Premio De Espana 2019",
                        "img/spain.jpg"),
                array(  "#",
                        "Monaco",
                        "Formula 1 Grand Prix De Monaco 2019",
                        "img/monaco.jpg"),
                array(  "#",
                        "Canada",
                        "Formula 1 Pirelli Grand Prix Du Canada 2019",
                        "img/canada.jpg"),
                array(  "#",
                        "France",
                        "Formula 1 Pirelli Grand Prix De France 2019",
                        "img/france.jpg"),
                array(  "#",
                        "Austria",
                        "Formula 1 Myworld Grosser Preis Von Osterreich 2019",
                        "img/austria.jpg"),
                array(  "#",
                        "United Kingdom",
                        "Formula 1 Rolex British Grand Prix 2019",
                        "img/UK.jpg"),
                array(  "#",
                        "Germany",
                        "Formula 1 Mercedes Benz Grosser Preis Von Deutschland 2019",
                        "img/germany.jpg"),
                array(  "#",
                        "Hungary",
                        "Formula 1 Rolex Magyar Nagydij 2019",
                        "img/hungary.jpg"),
                array(  "#",
                        "Belgium",
                        "Formula 1 Johnnie Walker Belgian Grand Prix 2019",
                        "img/belgium.jpg"),
                array(  "#",
                        "Italy",
                        "Formula 1 Gran Premio Heineken D'Italia 2019",
                        "img/italy.jpg"),
                array(  "#",
                        "Singapore",
                        "Formula 1 Singapore Airlines Singapore Grand Prix 2019",
                        "img/singapore.jpg"),
                array(  "#",
                        "Russian Federation",
                        "Formula 1 VTB Russian Grand Prix 2019",
                        "img/Russia.jpg"),
                array(  "#",
                        "Japan",
                        "Formula 1 Japanese Grand Prix 2019",
                        "img/japan.jpg"),
                array(  "#",
                        "Mexico",
                        "Formula 1 Gran Premio De Mexico 2019",
                        "img/mexico.jpg"),
                array(  "#",
                        "United States",
                        "Formula 1 United States Grand Prix 2019",
                        "img/US.jpg"),
                array(  "#",
                        "Brazil",
                        "Formula 1 Heineken Grande Premio Do Brasil 2019",
                        "img/brazil.jpg"),
                array(  "#",
                        "United Arab Emirates",
                        "Formula 1 Etihad Airways Abu Dhabi Grand Prix 2019",
                        "img/UAE.jpg")        
        );
?>