SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Ridion") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Ridion") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Ridion") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Ridion") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Ridion") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Ridion") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Ridion") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Ridion") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Ridion") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Ridion") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Ridion") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Ridion") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Ridion") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Ridion") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Ridion") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Ridion") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Ridion") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Ridion") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Ridion") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Ridion") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Ridion") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Ridion") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Ridion") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Ridion") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Ridion") AS "Punten" 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "DonkeyKonkey") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "DonkeyKonkey") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "DonkeyKonkey") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "DonkeyKonkey") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "DonkeyKonkey") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "DonkeyKonkey") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "DonkeyKonkey") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "DonkeyKonkey") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "DonkeyKonkey") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "DonkeyKonkey") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "DonkeyKonkey") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "DonkeyKonkey") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "DonkeyKonkey") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "DonkeyKonkey") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "DonkeyKonkey") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "DonkeyKonkey") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "DonkeyKonkey") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "DonkeyKonkey") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "DonkeyKonkey") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "DonkeyKonkey") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "DonkeyKonkey") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "DonkeyKonkey") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "DonkeyKonkey") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "DonkeyKonkey") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "DonkeyKonkey") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Dennis") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Dennis") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Dennis") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Dennis") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Dennis") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Dennis") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Dennis") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Dennis") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Dennis") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Dennis") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Dennis") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Dennis") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Dennis") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Dennis") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Dennis") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Dennis") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Dennis") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Dennis") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Dennis") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Dennis") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Dennis") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Dennis") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Dennis") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Dennis") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Dennis") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Pinguin") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Pinguin") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Pinguin") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Pinguin") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Pinguin") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Pinguin") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Pinguin") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Pinguin") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Pinguin") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Pinguin") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Pinguin") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Pinguin") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Pinguin") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Pinguin") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Pinguin") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Pinguin") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Pinguin") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Pinguin") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Pinguin") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Pinguin") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Pinguin") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Pinguin") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Pinguin") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Pinguin") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Pinguin") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Bikk3l") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Bikk3l") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Bikk3l") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Bikk3l") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Bikk3l") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Bikk3l") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Bikk3l") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Bikk3l") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Bikk3l") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Bikk3l") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Bikk3l") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Bikk3l") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Bikk3l") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Bikk3l") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Bikk3l") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Bikk3l") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Bikk3l") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Bikk3l") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Bikk3l") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Bikk3l") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Bikk3l") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Bikk3l") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Bikk3l") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Bikk3l") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Bikk3l") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Arris") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Arris") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Arris") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Arris") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Arris") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Arris") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Arris") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Arris") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Arris") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Arris") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Arris") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Arris") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Arris") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Arris") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Arris") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Arris") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Arris") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Arris") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Arris") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Arris") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Arris") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Arris") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Arris") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Arris") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Arris") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Heroism") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Heroism") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Heroism") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Heroism") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Heroism") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Heroism") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Heroism") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Heroism") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Heroism") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Heroism") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Heroism") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Heroism") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Heroism") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Heroism") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Heroism") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Heroism") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Heroism") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Heroism") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Heroism") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Heroism") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Heroism") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Heroism") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Heroism") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Heroism") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Heroism") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Battle On") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Battle On") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Battle On") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Battle On") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Battle On") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Battle On") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Battle On") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Battle On") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Battle On") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Battle On") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Battle On") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Battle On") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Battle On") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Battle On") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Battle On") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Battle On") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Battle On") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Battle On") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Battle On") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Battle On") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Battle On") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Battle On") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Battle On") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Battle On") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Battle On") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Jordiz64") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Jordiz64") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Jordiz64") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Jordiz64") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Jordiz64") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Jordiz64") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Jordiz64") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Jordiz64") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Jordiz64") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Jordiz64") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Jordiz64") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Jordiz64") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Jordiz64") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Jordiz64") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Jordiz64") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Jordiz64") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Jordiz64") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Jordiz64") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Jordiz64") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Jordiz64") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Jordiz64") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Jordiz64") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Jordiz64") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Jordiz64") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Jordiz64") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "JurdeV") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "JurdeV") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "JurdeV") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "JurdeV") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "JurdeV") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "JurdeV") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "JurdeV") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "JurdeV") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "JurdeV") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "JurdeV") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "JurdeV") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "JurdeV") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "JurdeV") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "JurdeV") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "JurdeV") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "JurdeV") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "JurdeV") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "JurdeV") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "JurdeV") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "JurdeV") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "JurdeV") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "JurdeV") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "JurdeV") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "JurdeV") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "JurdeV") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Kyreria") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Kyreria") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Kyreria") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Kyreria") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Kyreria") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Kyreria") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Kyreria") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Kyreria") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Kyreria") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Kyreria") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Kyreria") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Kyreria") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Kyreria") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Kyreria") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Kyreria") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Kyreria") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Kyreria") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Kyreria") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Kyreria") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Kyreria") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Kyreria") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Kyreria") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Kyreria") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Kyreria") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Kyreria") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "MOAB02") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "MOAB02") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "MOAB02") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "MOAB02") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "MOAB02") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "MOAB02") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "MOAB02") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "MOAB02") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "MOAB02") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "MOAB02") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "MOAB02") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "MOAB02") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "MOAB02") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "MOAB02") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "MOAB02") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "MOAB02") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "MOAB02") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "MOAB02") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "MOAB02") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "MOAB02") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "MOAB02") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "MOAB02") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "MOAB02") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "MOAB02") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "MOAB02") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Qumielo") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Qumielo") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Qumielo") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Qumielo") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Qumielo") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Qumielo") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Qumielo") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Qumielo") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Qumielo") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Qumielo") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Qumielo") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Qumielo") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Qumielo") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Qumielo") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Qumielo") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Qumielo") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Qumielo") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Qumielo") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Qumielo") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Qumielo") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Qumielo") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Qumielo") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Qumielo") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Qumielo") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Qumielo") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Rene9977") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Rene9977") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Rene9977") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Rene9977") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Rene9977") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Rene9977") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Rene9977") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Rene9977") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Rene9977") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Rene9977") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Rene9977") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Rene9977") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Rene9977") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Rene9977") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Rene9977") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Rene9977") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Rene9977") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Rene9977") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Rene9977") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Rene9977") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Rene9977") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Rene9977") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Rene9977") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Rene9977") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Rene9977") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Schapen") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Schapen") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Schapen") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Schapen") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Schapen") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Schapen") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Schapen") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Schapen") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Schapen") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Schapen") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Schapen") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Schapen") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Schapen") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Schapen") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Schapen") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Schapen") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Schapen") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Schapen") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Schapen") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Schapen") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Schapen") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Schapen") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Schapen") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Schapen") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Schapen") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "TheDutchTorpedo") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "TheDutchTorpedo") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "TheDutchTorpedo") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "TheDutchTorpedo") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "TheDutchTorpedo") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "TheDutchTorpedo") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "TheDutchTorpedo") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "TheDutchTorpedo") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "TheDutchTorpedo") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "TheDutchTorpedo") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "TheDutchTorpedo") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "TheDutchTorpedo") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "TheDutchTorpedo") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "TheDutchTorpedo") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "TheDutchTorpedo") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "TheDutchTorpedo") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "TheDutchTorpedo") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "TheDutchTorpedo") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "TheDutchTorpedo") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "TheDutchTorpedo") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "TheDutchTorpedo") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "TheDutchTorpedo") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "TheDutchTorpedo") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "TheDutchTorpedo") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "TheDutchTorpedo") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "TimToBeat") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "TimToBeat") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "TimToBeat") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "TimToBeat") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "TimToBeat") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "TimToBeat") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "TimToBeat") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "TimToBeat") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "TimToBeat") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "TimToBeat") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "TimToBeat") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "TimToBeat") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "TimToBeat") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "TimToBeat") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "TimToBeat") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "TimToBeat") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "TimToBeat") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "TimToBeat") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "TimToBeat") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "TimToBeat") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "TimToBeat") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "TimToBeat") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "TimToBeat") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "TimToBeat") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "TimToBeat") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Trivago") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Trivago") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Trivago") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Trivago") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Trivago") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Trivago") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Trivago") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Trivago") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Trivago") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Trivago") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Trivago") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Trivago") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Trivago") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Trivago") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Trivago") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Trivago") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Trivago") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Trivago") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Trivago") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Trivago") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Trivago") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Trivago") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Trivago") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Trivago") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Trivago") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Y_ram(NL)") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Y_ram(NL)") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Y_ram(NL)") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Y_ram(NL)") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Y_ram(NL)") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Y_ram(NL)") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Y_ram(NL)") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Y_ram(NL)") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Y_ram(NL)") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Y_ram(NL)") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Y_ram(NL)") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Y_ram(NL)") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Y_ram(NL)") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Y_ram(NL)") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Y_ram(NL)") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Y_ram(NL)") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Y_ram(NL)") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Y_ram(NL)") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Y_ram(NL)") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Y_ram(NL)") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Y_ram(NL)") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Y_ram(NL)") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Y_ram(NL)") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Y_ram(NL)") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Y_ram(NL)") AS Punten 
FROM race_results
UNION
SELECT DISTINCT  
            (SELECT Racenummer FROM drivers WHERE naam = "Demigod") AS "Nr",
            (SELECT DISTINCT driver  FROM race_results WHERE driver = "Demigod") AS "Coureur", 
            (SELECT plek  FROM race_results WHERE race_id = 1 AND driver = "Demigod") AS "AUS", 
            (SELECT plek  FROM race_results WHERE race_id = 2 AND driver = "Demigod") AS "BAH",
            (SELECT plek  FROM race_results WHERE race_id = 3 AND driver = "Demigod") AS "CHN",
            (SELECT plek  FROM race_results WHERE race_id = 4 AND driver = "Demigod") AS "AZE", 
            (SELECT plek  FROM race_results WHERE race_id = 5 AND driver = "Demigod") AS "SPA",
            (SELECT plek  FROM race_results WHERE race_id = 6 AND driver = "Demigod") AS "MON",
            (SELECT plek  FROM race_results WHERE race_id = 7 AND driver = "Demigod") AS "CAN", 
            (SELECT plek  FROM race_results WHERE race_id = 8 AND driver = "Demigod") AS "FRA",
            (SELECT plek  FROM race_results WHERE race_id = 9 AND driver = "Demigod") AS "OOS",
            (SELECT plek  FROM race_results WHERE race_id = 10 AND driver = "Demigod") AS "GBR", 
            (SELECT plek  FROM race_results WHERE race_id = 11 AND driver = "Demigod") AS "DUI",
            (SELECT plek  FROM race_results WHERE race_id = 12 AND driver = "Demigod") AS "HON",
            (SELECT plek  FROM race_results WHERE race_id = 13 AND driver = "Demigod") AS "BEL", 
            (SELECT plek  FROM race_results WHERE race_id = 14 AND driver = "Demigod") AS "ITA",
            (SELECT plek  FROM race_results WHERE race_id = 15 AND driver = "Demigod") AS "SIN",
            (SELECT plek  FROM race_results WHERE race_id = 16 AND driver = "Demigod") AS "RUS", 
            (SELECT plek  FROM race_results WHERE race_id = 17 AND driver = "Demigod") AS "JAP",
            (SELECT plek  FROM race_results WHERE race_id = 18 AND driver = "Demigod") AS "MEX",
            (SELECT plek  FROM race_results WHERE race_id = 19 AND driver = "Demigod") AS "USA", 
            (SELECT plek  FROM race_results WHERE race_id = 20 AND driver = "Demigod") AS "BRA",
            (SELECT plek  FROM race_results WHERE race_id = 21 AND driver = "Demigod") AS "ABU",
            (SELECT SUM(plek) FROM race_results WHERE driver = "Demigod") AS TPVR,
            (SELECT SUM(snelste_ronde_punten+race_punten-straf_punten) FROM race_results WHERE driver LIKE "Demigod") AS Punten 
FROM race_results
ORDER BY Punten DESC, TPVR;