INSERT INTO `race_results` (`race_id`, `driver`, `snelste_ronde`, `tijd`, `plek`, `snelste_ronde_punten`, `race_punten`, `straf_punten`) VALUES
(1, 'Ridion',           '-',    '-',    1,      1,      25,         NULL),
(1, 'Qumielo',          '-',    '-',    2,      NULL,      18,      NULL),
(1, 'TimToBeat',        '-',    '-',    3,      NULL,      15,      NULL),
(1, 'DonkeyKonkey',     '-',    '-',    4,      NULL,      12,      NULL),
(1, 'Demigod',          '-',    '-',    5,      NULL,      10,      NULL),
(1, 'Pinguin',          '-',    '-',    6,      NULL,      8,       NULL),
(1, 'JordiZ64',         '-',    '-',    7,      NULL,      6,       NULL),
(1, 'JurdeV',           '-',    '-',    8,      NULL,      4,       NULL),
(1, 'Trivago',          '-',    '-',    9,      NULL,      2,       NULL),
(1, 'Dennis',           '-',    '-',    10,     NULL,      1,       NULL),
(1, 'MOAB02',           '-',    '-',    11,     NULL,      0,       NULL),
(1, 'Bikk3l',           '-',    '-',    12,     NULL,      0,       NULL),
(1, 'Battle On',        '-',    '-',    13,     NULL,      0,       NULL),
(1, 'Rene9977',         '-',    '-',    14,     NULL,      0,       NULL),
(1, 'Arris',            '-',    '-',    15,     NULL,      0,       NULL),
(1, 'Heroism',          '-',    '-',    16,     NULL,      0,       NULL),
(1, 'Schapen',          '-',    '-',    17,     NULL,      0,       NULL),
(1, 'TheDutchTorpedo',  '-',    '-',    18,     NULL,      0,       NULL),
(1, 'Kyreria',          '-',    '-',    19,     NULL,      0,       NULL),
(1, 'Y_ram(NL)',        '-',    '-',    20,     NULL,      0,       NULL);